#define OPCODE_ERROR 5
#define OPCODE_ACK 4
#define OPCODE_DATA 3
#define OPCODE_WRQ 2
#define OPCODE_RRQ 1
#define MAX_SIZE 512

// TFTP Error Codes
#define TFTP_ERROR_NOT_DEFINED 0
#define TFTP_ERROR_FILE_NOT_FOUND 1
#define TFTP_ERROR_ACCESS_VIOLATION 2
#define TFTP_ERROR_DISK_FULL 3
#define TFTP_ERROR_ILLEGAL_OP 4
#define TFTP_ERROR_UNKNOWN_ID 5
#define TFTP_ERROR_FILE_EXISTS 6
#define TFTP_ERROR_NO_USER 7

#define BLOCK_SIZE 2